/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ufes.view;

import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author daniel
 */
public class DadosMediosView extends javax.swing.JInternalFrame {

    /**
     * Creates new form DadosMediosView
     */
    public DadosMediosView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tx_medios_temperatura = new javax.swing.JLabel();
        tx_medios_pressao = new javax.swing.JLabel();
        tx_medios_umidade = new javax.swing.JLabel();
        tx_medios_nroRegistros = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setTitle("Dados Medios");

        jLabel13.setText("Temperatura");

        jLabel14.setText("Umidade");

        jLabel15.setText("Pressao");

        jLabel16.setText("Numero de registros");

        tx_medios_temperatura.setText("jLabel1");

        tx_medios_pressao.setText("jLabel1");

        tx_medios_umidade.setText("jLabel1");

        tx_medios_nroRegistros.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tx_medios_temperatura, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tx_medios_umidade, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tx_medios_pressao, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tx_medios_nroRegistros, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tx_medios_temperatura)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tx_medios_umidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tx_medios_pressao)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tx_medios_nroRegistros))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel tx_medios_nroRegistros;
    private javax.swing.JLabel tx_medios_pressao;
    private javax.swing.JLabel tx_medios_temperatura;
    private javax.swing.JLabel tx_medios_umidade;
    // End of variables declaration//GEN-END:variables

    public JLabel getTx_medios_nroRegistros() {
        return tx_medios_nroRegistros;
    }

    public JLabel getTx_medios_pressao() {
        return tx_medios_pressao;
    }

    public JLabel getTx_medios_temperatura() {
        return tx_medios_temperatura;
    }

    public JLabel getTx_medios_umidade() {
        return tx_medios_umidade;
    }



}
