/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ufes.view;

import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author daniel
 */
public class UltimaAtualizacaoView extends javax.swing.JInternalFrame {

    /**
     * Creates new form DadosMediosView
     */
    public UltimaAtualizacaoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tx_atualizacao_Umidade = new javax.swing.JLabel();
        tx_atualizacao_Temperatura = new javax.swing.JLabel();
        tx_atualizacao_Pressao = new javax.swing.JLabel();
        tx_atualizacao_Data = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Ultima atualizacao do tempo");

        jLabel7.setText("Data");

        jLabel8.setText("Temperatura");

        jLabel9.setText("Umidade");

        jLabel10.setText("Pressao");

        tx_atualizacao_Umidade.setText("jLabel1");

        tx_atualizacao_Temperatura.setText("jLabel1");

        tx_atualizacao_Pressao.setText("jLabel1");

        tx_atualizacao_Data.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addGap(18, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tx_atualizacao_Pressao)
                    .addComponent(tx_atualizacao_Data)
                    .addComponent(tx_atualizacao_Temperatura)
                    .addComponent(tx_atualizacao_Umidade))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tx_atualizacao_Data))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tx_atualizacao_Temperatura))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tx_atualizacao_Umidade))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tx_atualizacao_Pressao))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel tx_atualizacao_Data;
    private javax.swing.JLabel tx_atualizacao_Pressao;
    private javax.swing.JLabel tx_atualizacao_Temperatura;
    private javax.swing.JLabel tx_atualizacao_Umidade;
    // End of variables declaration//GEN-END:variables

    public JLabel getTx_atualizacao_Data() {
        return tx_atualizacao_Data;
    }

    public JLabel getTx_atualizacao_Pressao() {
        return tx_atualizacao_Pressao;
    }

    public JLabel getTx_atualizacao_Temperatura() {
        return tx_atualizacao_Temperatura;
    }

    public JLabel getTx_atualizacao_Umidade() {
        return tx_atualizacao_Umidade;
    }
}
